### ISSUE TITLE
Cannot resolve dependencies

### ISSUE THREAD

**Issue by jlcheng** [avh4/hero-extant#1]
This is the error I get

```
[ERROR] Failed to execute goal on project hero-extant: Could not resolve dependencies for project net.avh4.rpg.generators:hero-extant:jar:0.0.4-SNAPSHOT: Could not find artifact net.avh4.rpg:map-toolkit:jar:0.0.1-SNAPSHOT in sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]
```

Where can I find the map-tookit artifact? Do I need to checkout the map-toolkit project and build & deploy to a local repository?

**Comment by avh4** [comment]
It's at https://github.com/avh4/map-toolkit

If you clone and 'mvn install' it, then you should be able to build hero-extant.  I'll update the README.

**Comment by avh4** [comment]
Updated instructions: https://github.com/avh4/hero-extant/blob/master/README.txt
